// Code generated by MockGen. DO NOT EDIT.
// Source: service.go

// Package service_mock is a generated GoMock package.
package service_mock

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	model "github.com/vvv9912/ya-go-musthave-metrics-tpl.git/internal/model"
)

// MockGaugeStorager is a mock of GaugeStorager interface.
type MockGaugeStorager struct {
	ctrl     *gomock.Controller
	recorder *MockGaugeStoragerMockRecorder
}

// MockGaugeStoragerMockRecorder is the mock recorder for MockGaugeStorager.
type MockGaugeStoragerMockRecorder struct {
	mock *MockGaugeStorager
}

// NewMockGaugeStorager creates a new mock instance.
func NewMockGaugeStorager(ctrl *gomock.Controller) *MockGaugeStorager {
	mock := &MockGaugeStorager{ctrl: ctrl}
	mock.recorder = &MockGaugeStoragerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGaugeStorager) EXPECT() *MockGaugeStoragerMockRecorder {
	return m.recorder
}

// GetAllGauge mocks base method.
func (m *MockGaugeStorager) GetAllGauge(ctx context.Context) (map[string]float64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllGauge", ctx)
	ret0, _ := ret[0].(map[string]float64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllGauge indicates an expected call of GetAllGauge.
func (mr *MockGaugeStoragerMockRecorder) GetAllGauge(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllGauge", reflect.TypeOf((*MockGaugeStorager)(nil).GetAllGauge), ctx)
}

// GetGauge mocks base method.
func (m *MockGaugeStorager) GetGauge(ctx context.Context, key string) (float64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGauge", ctx, key)
	ret0, _ := ret[0].(float64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetGauge indicates an expected call of GetGauge.
func (mr *MockGaugeStoragerMockRecorder) GetGauge(ctx, key interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGauge", reflect.TypeOf((*MockGaugeStorager)(nil).GetGauge), ctx, key)
}

// UpdateGauge mocks base method.
func (m *MockGaugeStorager) UpdateGauge(ctx context.Context, key string, val float64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateGauge", ctx, key, val)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateGauge indicates an expected call of UpdateGauge.
func (mr *MockGaugeStoragerMockRecorder) UpdateGauge(ctx, key, val interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateGauge", reflect.TypeOf((*MockGaugeStorager)(nil).UpdateGauge), ctx, key, val)
}

// MockCounterStorager is a mock of CounterStorager interface.
type MockCounterStorager struct {
	ctrl     *gomock.Controller
	recorder *MockCounterStoragerMockRecorder
}

// MockCounterStoragerMockRecorder is the mock recorder for MockCounterStorager.
type MockCounterStoragerMockRecorder struct {
	mock *MockCounterStorager
}

// NewMockCounterStorager creates a new mock instance.
func NewMockCounterStorager(ctrl *gomock.Controller) *MockCounterStorager {
	mock := &MockCounterStorager{ctrl: ctrl}
	mock.recorder = &MockCounterStoragerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCounterStorager) EXPECT() *MockCounterStoragerMockRecorder {
	return m.recorder
}

// GetAllCounter mocks base method.
func (m *MockCounterStorager) GetAllCounter(ctx context.Context) (map[string]uint64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllCounter", ctx)
	ret0, _ := ret[0].(map[string]uint64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllCounter indicates an expected call of GetAllCounter.
func (mr *MockCounterStoragerMockRecorder) GetAllCounter(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllCounter", reflect.TypeOf((*MockCounterStorager)(nil).GetAllCounter), ctx)
}

// GetCounter mocks base method.
func (m *MockCounterStorager) GetCounter(ctx context.Context, key string) (uint64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCounter", ctx, key)
	ret0, _ := ret[0].(uint64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCounter indicates an expected call of GetCounter.
func (mr *MockCounterStoragerMockRecorder) GetCounter(ctx, key interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCounter", reflect.TypeOf((*MockCounterStorager)(nil).GetCounter), ctx, key)
}

// UpdateCounter mocks base method.
func (m *MockCounterStorager) UpdateCounter(ctx context.Context, key string, val uint64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateCounter", ctx, key, val)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateCounter indicates an expected call of UpdateCounter.
func (mr *MockCounterStoragerMockRecorder) UpdateCounter(ctx, key, val interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateCounter", reflect.TypeOf((*MockCounterStorager)(nil).UpdateCounter), ctx, key, val)
}

// MockNotifierSend is a mock of NotifierSend interface.
type MockNotifierSend struct {
	ctrl     *gomock.Controller
	recorder *MockNotifierSendMockRecorder
}

// MockNotifierSendMockRecorder is the mock recorder for MockNotifierSend.
type MockNotifierSendMockRecorder struct {
	mock *MockNotifierSend
}

// NewMockNotifierSend creates a new mock instance.
func NewMockNotifierSend(ctrl *gomock.Controller) *MockNotifierSend {
	mock := &MockNotifierSend{ctrl: ctrl}
	mock.recorder = &MockNotifierSendMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNotifierSend) EXPECT() *MockNotifierSendMockRecorder {
	return m.recorder
}

// NotifierPending mocks base method.
func (m *MockNotifierSend) NotifierPending(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NotifierPending", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// NotifierPending indicates an expected call of NotifierPending.
func (mr *MockNotifierSendMockRecorder) NotifierPending(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NotifierPending", reflect.TypeOf((*MockNotifierSend)(nil).NotifierPending), ctx)
}

// MockMetrics is a mock of Metrics interface.
type MockMetrics struct {
	ctrl     *gomock.Controller
	recorder *MockMetricsMockRecorder
}

// MockMetricsMockRecorder is the mock recorder for MockMetrics.
type MockMetricsMockRecorder struct {
	mock *MockMetrics
}

// NewMockMetrics creates a new mock instance.
func NewMockMetrics(ctrl *gomock.Controller) *MockMetrics {
	mock := &MockMetrics{ctrl: ctrl}
	mock.recorder = &MockMetricsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMetrics) EXPECT() *MockMetricsMockRecorder {
	return m.recorder
}

// GetCounter mocks base method.
func (m *MockMetrics) GetCounter(ctx context.Context, key string) (uint64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCounter", ctx, key)
	ret0, _ := ret[0].(uint64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCounter indicates an expected call of GetCounter.
func (mr *MockMetricsMockRecorder) GetCounter(ctx, key interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCounter", reflect.TypeOf((*MockMetrics)(nil).GetCounter), ctx, key)
}

// GetGauge mocks base method.
func (m *MockMetrics) GetGauge(ctx context.Context, key string) (float64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGauge", ctx, key)
	ret0, _ := ret[0].(float64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetGauge indicates an expected call of GetGauge.
func (mr *MockMetricsMockRecorder) GetGauge(ctx, key interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGauge", reflect.TypeOf((*MockMetrics)(nil).GetGauge), ctx, key)
}

// GetMetrics mocks base method.
func (m *MockMetrics) GetMetrics(ctx context.Context, metrics model.Metrics) (model.Metrics, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMetrics", ctx, metrics)
	ret0, _ := ret[0].(model.Metrics)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMetrics indicates an expected call of GetMetrics.
func (mr *MockMetricsMockRecorder) GetMetrics(ctx, metrics interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMetrics", reflect.TypeOf((*MockMetrics)(nil).GetMetrics), ctx, metrics)
}

// PutCounter mocks base method.
func (m *MockMetrics) PutCounter(ctx context.Context, key string, val uint64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PutCounter", ctx, key, val)
	ret0, _ := ret[0].(error)
	return ret0
}

// PutCounter indicates an expected call of PutCounter.
func (mr *MockMetricsMockRecorder) PutCounter(ctx, key, val interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PutCounter", reflect.TypeOf((*MockMetrics)(nil).PutCounter), ctx, key, val)
}

// PutGauge mocks base method.
func (m *MockMetrics) PutGauge(ctx context.Context, key string, val float64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PutGauge", ctx, key, val)
	ret0, _ := ret[0].(error)
	return ret0
}

// PutGauge indicates an expected call of PutGauge.
func (mr *MockMetricsMockRecorder) PutGauge(ctx, key, val interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PutGauge", reflect.TypeOf((*MockMetrics)(nil).PutGauge), ctx, key, val)
}

// PutMetrics mocks base method.
func (m *MockMetrics) PutMetrics(ctx context.Context, metrics model.Metrics) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PutMetrics", ctx, metrics)
	ret0, _ := ret[0].(error)
	return ret0
}

// PutMetrics indicates an expected call of PutMetrics.
func (mr *MockMetricsMockRecorder) PutMetrics(ctx, metrics interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PutMetrics", reflect.TypeOf((*MockMetrics)(nil).PutMetrics), ctx, metrics)
}

// SendMetricstoFile mocks base method.
func (m *MockMetrics) SendMetricstoFile(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendMetricstoFile", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendMetricstoFile indicates an expected call of SendMetricstoFile.
func (mr *MockMetricsMockRecorder) SendMetricstoFile(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendMetricstoFile", reflect.TypeOf((*MockMetrics)(nil).SendMetricstoFile), ctx)
}

// MockStore is a mock of Store interface.
type MockStore struct {
	ctrl     *gomock.Controller
	recorder *MockStoreMockRecorder
}

// MockStoreMockRecorder is the mock recorder for MockStore.
type MockStoreMockRecorder struct {
	mock *MockStore
}

// NewMockStore creates a new mock instance.
func NewMockStore(ctrl *gomock.Controller) *MockStore {
	mock := &MockStore{ctrl: ctrl}
	mock.recorder = &MockStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStore) EXPECT() *MockStoreMockRecorder {
	return m.recorder
}

// Ping mocks base method.
func (m *MockStore) Ping(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Ping", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Ping indicates an expected call of Ping.
func (mr *MockStoreMockRecorder) Ping(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Ping", reflect.TypeOf((*MockStore)(nil).Ping), ctx)
}

// UpdateMetricsBatch mocks base method.
func (m *MockStore) UpdateMetricsBatch(ctx context.Context, metrics []model.Metrics) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateMetricsBatch", ctx, metrics)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateMetricsBatch indicates an expected call of UpdateMetricsBatch.
func (mr *MockStoreMockRecorder) UpdateMetricsBatch(ctx, metrics interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateMetricsBatch", reflect.TypeOf((*MockStore)(nil).UpdateMetricsBatch), ctx, metrics)
}
