// Code generated by protoc-gen-go-grpcServer. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpcServer v1.3.0
// - protoc             v3.12.4
// source: proto/metrics.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpcServer package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Metrics_UpdateGauge_FullMethodName       = "/grpcServer.Metrics/UpdateGauge"
	Metrics_UpdateCounter_FullMethodName     = "/grpcServer.Metrics/UpdateCounter"
	Metrics_UpdateGaugeJson_FullMethodName   = "/grpcServer.Metrics/UpdateGaugeJson"
	Metrics_UpdateCounterJson_FullMethodName = "/grpcServer.Metrics/UpdateCounterJson"
	Metrics_UpdatesBatched_FullMethodName    = "/grpcServer.Metrics/UpdatesBatched"
)

// MetricsClient is the client API for Metrics service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MetricsClient interface {
	UpdateGauge(ctx context.Context, in *Update, opts ...grpc.CallOption) (*Response, error)
	UpdateCounter(ctx context.Context, in *Update, opts ...grpc.CallOption) (*Response, error)
	UpdateGaugeJson(ctx context.Context, in *UpdateSlice, opts ...grpc.CallOption) (*Response, error)
	UpdateCounterJson(ctx context.Context, in *UpdateSlice, opts ...grpc.CallOption) (*Response, error)
	UpdatesBatched(ctx context.Context, in *UpdateSlice, opts ...grpc.CallOption) (*Response, error)
}

type metricsClient struct {
	cc grpc.ClientConnInterface
}

func NewMetricsClient(cc grpc.ClientConnInterface) MetricsClient {
	return &metricsClient{cc}
}

func (c *metricsClient) UpdateGauge(ctx context.Context, in *Update, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, Metrics_UpdateGauge_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metricsClient) UpdateCounter(ctx context.Context, in *Update, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, Metrics_UpdateCounter_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metricsClient) UpdateGaugeJson(ctx context.Context, in *UpdateSlice, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, Metrics_UpdateGaugeJson_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metricsClient) UpdateCounterJson(ctx context.Context, in *UpdateSlice, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, Metrics_UpdateCounterJson_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metricsClient) UpdatesBatched(ctx context.Context, in *UpdateSlice, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, Metrics_UpdatesBatched_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MetricsServer is the server API for Metrics service.
// All implementations must embed UnimplementedMetricsServer
// for forward compatibility
type MetricsServer interface {
	UpdateGauge(context.Context, *Update) (*Response, error)
	UpdateCounter(context.Context, *Update) (*Response, error)
	UpdateGaugeJson(context.Context, *UpdateSlice) (*Response, error)
	UpdateCounterJson(context.Context, *UpdateSlice) (*Response, error)
	UpdatesBatched(context.Context, *UpdateSlice) (*Response, error)
	mustEmbedUnimplementedMetricsServer()
}

// UnimplementedMetricsServer must be embedded to have forward compatible implementations.
type UnimplementedMetricsServer struct {
}

func (UnimplementedMetricsServer) UpdateGauge(context.Context, *Update) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateGauge not implemented")
}
func (UnimplementedMetricsServer) UpdateCounter(context.Context, *Update) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateCounter not implemented")
}
func (UnimplementedMetricsServer) UpdateGaugeJson(context.Context, *UpdateSlice) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateGaugeJson not implemented")
}
func (UnimplementedMetricsServer) UpdateCounterJson(context.Context, *UpdateSlice) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateCounterJson not implemented")
}
func (UnimplementedMetricsServer) UpdatesBatched(context.Context, *UpdateSlice) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdatesBatched not implemented")
}
func (UnimplementedMetricsServer) mustEmbedUnimplementedMetricsServer() {}

// UnsafeMetricsServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MetricsServer will
// result in compilation errors.
type UnsafeMetricsServer interface {
	mustEmbedUnimplementedMetricsServer()
}

func RegisterMetricsServer(s grpc.ServiceRegistrar, srv MetricsServer) {
	s.RegisterService(&Metrics_ServiceDesc, srv)
}

func _Metrics_UpdateGauge_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Update)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetricsServer).UpdateGauge(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Metrics_UpdateGauge_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetricsServer).UpdateGauge(ctx, req.(*Update))
	}
	return interceptor(ctx, in, info, handler)
}

func _Metrics_UpdateCounter_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Update)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetricsServer).UpdateCounter(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Metrics_UpdateCounter_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetricsServer).UpdateCounter(ctx, req.(*Update))
	}
	return interceptor(ctx, in, info, handler)
}

func _Metrics_UpdateGaugeJson_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateSlice)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetricsServer).UpdateGaugeJson(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Metrics_UpdateGaugeJson_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetricsServer).UpdateGaugeJson(ctx, req.(*UpdateSlice))
	}
	return interceptor(ctx, in, info, handler)
}

func _Metrics_UpdateCounterJson_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateSlice)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetricsServer).UpdateCounterJson(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Metrics_UpdateCounterJson_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetricsServer).UpdateCounterJson(ctx, req.(*UpdateSlice))
	}
	return interceptor(ctx, in, info, handler)
}

func _Metrics_UpdatesBatched_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateSlice)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetricsServer).UpdatesBatched(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Metrics_UpdatesBatched_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetricsServer).UpdatesBatched(ctx, req.(*UpdateSlice))
	}
	return interceptor(ctx, in, info, handler)
}

// Metrics_ServiceDesc is the grpc.ServiceDesc for Metrics service.
// It's only intended for direct use with grpcServer.RegisterService,
// and not to be introspected or modified (even as a copy)
var Metrics_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "grpcServer.Metrics",
	HandlerType: (*MetricsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UpdateGauge",
			Handler:    _Metrics_UpdateGauge_Handler,
		},
		{
			MethodName: "UpdateCounter",
			Handler:    _Metrics_UpdateCounter_Handler,
		},
		{
			MethodName: "UpdateGaugeJson",
			Handler:    _Metrics_UpdateGaugeJson_Handler,
		},
		{
			MethodName: "UpdateCounterJson",
			Handler:    _Metrics_UpdateCounterJson_Handler,
		},
		{
			MethodName: "UpdatesBatched",
			Handler:    _Metrics_UpdatesBatched_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/metrics.proto",
}
